create table if not exists public.ganpati_year_data (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  year integer not null,
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, year)
);

alter table public.ganpati_year_data enable row level security;

create policy "Users can read own year data"
on public.ganpati_year_data
for select
using (auth.uid() = user_id);

create policy "Users can insert own year data"
on public.ganpati_year_data
for insert
with check (auth.uid() = user_id);

create policy "Users can update own year data"
on public.ganpati_year_data
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);
